# Generated by Django 2.0.7 on 2018-07-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0019_auto_20180718_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
                ('cvv', models.CharField(max_length=100)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_username', models.CharField(max_length=100)),
                ('date_transacted', models.DateTimeField()),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Caterer')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Consumer')),
            ],
        ),
    ]
