# Generated by Django 2.0.7 on 2018-07-18 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardtransaction',
            old_name='card_holder',
            new_name='consumer',
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='date_transacted',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 3, 10, 25, 910618, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
