# Generated by Django 2.0.7 on 2018-07-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180718_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='card_holder',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
