# Generated by Django 2.0.7 on 2018-07-18 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20180718_0156'),
        ('payment', '0003_creditcardtransaction_card_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='caterer',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='registration.Caterer'),
            preserve_default=False,
        ),
    ]
