# Generated by Django 2.0.6 on 2018-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_owned_by_consumer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
