# Generated by Django 2.0.6 on 2018-07-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0006_auto_20180629_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_body', models.CharField(max_length=1000)),
                ('review_rating', models.IntegerField()),
                ('review_date_submitted', models.DateTimeField(verbose_name='date submitted')),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Caterer')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Consumer')),
            ],
        ),
    ]
