# Generated by Django 2.0.6 on 2018-07-09 02:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20180709_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 2, 30, 59, 834334, tzinfo=utc), editable=False, verbose_name='date submited'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 2, 31, 3, 387908, tzinfo=utc), editable=False, verbose_name='date submited'),
            preserve_default=False,
        ),
    ]
