# Generated by Django 2.0.6 on 2018-06-26 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatrUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('catruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.CatrUser')),
                ('business_name', models.CharField(max_length=100)),
                ('business_description', models.CharField(max_length=1000)),
                ('province_address', models.CharField(max_length=100)),
                ('municipality_address', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            bases=('registration.catruser',),
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('catruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.CatrUser')),
            ],
            bases=('registration.catruser',),
        ),
        migrations.AddField(
            model_name='catruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
