# Generated by Django 2.0.6 on 2018-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='badge',
            field=models.IntegerField(default=0),
        ),
    ]
