# Generated by Django 2.0.6 on 2018-06-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180626_0553'),
        ('registration', '0003_auto_20180626_0614'),
    ]

    operations = [
    ]
