# Generated by Django 2.0.6 on 2018-06-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_merge_20180626_0745'),
        ('registration', '0004_merge_20180626_0735'),
    ]

    operations = [
    ]
