# Generated by Django 2.0.6 on 2018-06-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('registration', '0005_merge_20180626_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Caterer')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Course')),
            ],
        ),
        migrations.AddField(
            model_name='caterer',
            name='courses',
            field=models.ManyToManyField(through='registration.Menu', to='orders.Course'),
        ),
    ]
