# Generated by Django 2.0.6 on 2018-07-02 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_package'),
        ('registration', '0006_auto_20180629_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='package',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='orders.Package'),
            preserve_default=False,
        ),
    ]
