# Generated by Django 2.0.6 on 2018-07-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180703_0226'),
        ('registration', '0008_consumer_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Menu')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Tray')),
            ],
        ),
    ]
