# Generated by Django 2.0.6 on 2018-07-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_item_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='badge',
            new_name='consumer_badge',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='date_added',
            new_name='menu_date_added',
        ),
    ]
