# Generated by Django 2.0.6 on 2018-07-09 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20180704_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='catruser',
            name='user_type',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)]),
            preserve_default=False,
        ),
    ]
