# Generated by Django 2.0.6 on 2018-07-09 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_catruser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catruser',
            name='user_type',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
