# Generated by Django 2.0.6 on 2018-07-10 06:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_binary',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
