# Generated by Django 2.0.6 on 2018-07-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180711_0658'),
        ('registration', '0016_auto_20180710_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.History')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Tray')),
            ],
        ),
    ]
