# Generated by Django 2.0.6 on 2018-07-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='caterer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Caterer'),
        ),
    ]
