# Generated by Django 2.0.7 on 2018-07-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_transaction_caterer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_event_building_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_event_street_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_event_unit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_other_instructions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
