# Generated by Django 2.0.7 on 2018-07-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20180718_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Menu'),
        ),
    ]
