# Generated by Django 2.0.6 on 2018-07-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.History')),
            ],
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Date used')),
                ('tray_cumulative_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='date_created',
            new_name='package_date_created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Tray'),
        ),
        migrations.AddField(
            model_name='item',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Tray'),
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Package'),
        ),
    ]
