# Generated by Django 2.0.6 on 2018-07-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180703_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='package',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tray',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
