# Generated by Django 2.0.6 on 2018-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180703_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_unit',
            field=models.CharField(default='unit', max_length=20),
            preserve_default=False,
        ),
    ]
