# Generated by Django 2.0.6 on 2018-07-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_course_course_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='points',
            new_name='history_points',
        ),
    ]
