# Generated by Django 2.0.6 on 2018-07-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180704_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='history',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tray',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
