# Generated by Django 2.0.7 on 2018-07-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20180718_0816'),
        ('orders', '0009_course_course_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
